// flow-typed signature: 9de4db8e88bc4773994aa455b79f9f92
// flow-typed version: <<STUB>>/ag-grid-react_v^18.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ag-grid-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ag-grid-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ag-grid-react/gulpfile' {
  declare module.exports: any;
}

declare module 'ag-grid-react/lib/agGridColumn' {
  declare module.exports: any;
}

declare module 'ag-grid-react/lib/agGridReact' {
  declare module.exports: any;
}

declare module 'ag-grid-react/lib/agReactComponent' {
  declare module.exports: any;
}

declare module 'ag-grid-react/lib/interfaces' {
  declare module.exports: any;
}

declare module 'ag-grid-react/lib/main' {
  declare module.exports: any;
}

declare module 'ag-grid-react/main' {
  declare module.exports: any;
}

declare module 'ag-grid-react/umd/ag-grid-react.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ag-grid-react/gulpfile.js' {
  declare module.exports: $Exports<'ag-grid-react/gulpfile'>;
}
declare module 'ag-grid-react/lib/agGridColumn.js' {
  declare module.exports: $Exports<'ag-grid-react/lib/agGridColumn'>;
}
declare module 'ag-grid-react/lib/agGridReact.js' {
  declare module.exports: $Exports<'ag-grid-react/lib/agGridReact'>;
}
declare module 'ag-grid-react/lib/agReactComponent.js' {
  declare module.exports: $Exports<'ag-grid-react/lib/agReactComponent'>;
}
declare module 'ag-grid-react/lib/interfaces.js' {
  declare module.exports: $Exports<'ag-grid-react/lib/interfaces'>;
}
declare module 'ag-grid-react/lib/main.js' {
  declare module.exports: $Exports<'ag-grid-react/lib/main'>;
}
declare module 'ag-grid-react/main.js' {
  declare module.exports: $Exports<'ag-grid-react/main'>;
}
declare module 'ag-grid-react/umd/ag-grid-react.min.js' {
  declare module.exports: $Exports<'ag-grid-react/umd/ag-grid-react.min'>;
}
