// flow-typed signature: e2b659e92678e8c4e5f410c3b1792ded
// flow-typed version: <<STUB>>/react-dom-factories_v^1.0.2/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dom-factories'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dom-factories' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-dom-factories/index' {
  declare module.exports: $Exports<'react-dom-factories'>;
}
declare module 'react-dom-factories/index.js' {
  declare module.exports: $Exports<'react-dom-factories'>;
}
